### ISSUE TITLE
input for DREME

### ISSUE THREAD

**Issue by smb20200615** [VishnuRaghuram94/AgrVATE#10]
Hello,

Is it possible to adapt your tool for other staph species? If so, what would be the appropriate input to DREME?

Best wishes,

**Comment by VishnuRaghuram94** [comment]
Hello, 

Yes that's on my list for future things to do! The input for DREME would be _agr_ operons of known _agr_ groups. 

For example: 
`dreme -k 31 -e 0.0001 -m 15 -dna -oc ./dreme_gp1 -p gp1_operon.fna -n gp1_negative_operon.fna`

This would output fifteen 31mers that are enriched in only the group 1 operons ( `gp1_operon.fna` ) compared to "NOT" group 1 operons ( `gp1_negative_operon.fna` ) - which is a collection of every other _agr_ operon EXCEPT group 1. This would need to be repeated for every _agr_ group for that given species. And this entire process would need to be repeated for each species. 

However DREME has been deprecated since the development of AgrVATE so I will be looking at alternatives.  Please feel free to let me know if you have any suggestions! 

Vishnu

**Comment by smb20200615** [comment]
Thank you so much for your quick reply. 
I am now getting this error when I try to build the database. Do you know what could be going wrong?
```
Counting positive sequences with each word...
Counting negative sequences with each word...
Applying Fisher's Exact Test to 2679 words...
Generalizing top 100 of 2679 REs to 1 ambiguous characters...
Computing exact p-values for 0 REs...
Best RE was AAAAAAAATGTTATCTCGGGTGTTGTAATAG CTATTACAACACCCGAGATAACATTTTTTTT p-value= 3.3e-001 E-value= 8.9e+002 Unerased_E-value= 8.9e+002
Stopping due to hitting the maximum evalue.
0 motifs with E-value < 0.0001 found in 0.8 seconds.
Creating HTML file.
```
Also I didn't see a definition for what you mean by canonical Agr. Would you mind explaining what you mean by it and why it is important? And again very interesting paper on biorxiv/tool!

**Comment by VishnuRaghuram94** [comment]
Can you send me your input files and the exact command you used? It looks like it's not finding any unique motifs. 

By "canonical" agr I mean an agr operon sequence that does not contain any frameshift mutations and reflects the most commonly observed agr operon sequence for a given agr group. 

Thank you! Please let me know if you have any more questions

Vishnu
