### ISSUE TITLE
snippy not running

### ISSUE THREAD

**Issue by micaela-m** [VishnuRaghuram94/AgrVATE#11]
Column 7 of output returns "fail". All other outputs are returning "pass". I am running on mummer as I cannot download USearch on my current MacOS software.
Snippy is installed correctly as version 3.1 
Please could you advise?

**Comment by VishnuRaghuram94** [comment]
Hi Micaela, 

Thanks for raising the issue. The problem comes from either snippy not running correctly, or from mummer not being able to extract an intact _agr_ operon. 

Does `snippy --check`  report any issues with the dependencies? Can you share your snippy log file? Nevertheless I highly recommend updating snippy to the latest version (4.6). I think some snippy parameters used by agrVATE were not available in older versions of snippy. 

Please let me know if this works for you.

**Comment by micaela-m** [comment]
Hi, 

Thanks for this. I have now updated snippy to 4.6.0 and mummer is showing as pass, but it is still failing to find the agr operon. I am sharing the mummer file, there is no snippy log file and the blast n file is empty.

[FRUSA-1__fna-2-mummer-log.txt](https://github.com/VishnuRaghuram94/AgrVATE/files/7409293/FRUSA-1__fna-2-mummer-log.txt)

Many thanks, 

Micaela

**Comment by VishnuRaghuram94** [comment]
Hi Micaela, 

I think what is happening is that mummer is running and producing an alignment but the alignment is broken, possibly due to indels in your query genome's _agr_ operon. snippy only runs if an intact contiguous _agr_ operon is extracted. However, mummer runs a SNP call on it's own (out.snps), which you should see in the  mummer folder. 

I do have to mention that the mummer implementation is still in beta and is something that I am working on improving. While I understand that not everyone has this option, for best results I recommend using a system compatible with usearch. 

EDIT: I have pushed a release where a message is displayed if the mummer alignment is broken (discontiguous) but the resulting fragments are still passed to snippy for variant calling. This will however miss variants in the mummer alignment gaps.

Vishnu

**Comment by AhmedElsherbini** [comment]
Hi Vishnu,

I have trouble running snippy inside my environment 
so I got this error when I run snippy
Can't locate Bio/SeqIO.pm in @INC (you may need to install the Bio::SeqIO module) (@INC contains: /home/ahmed/anaconda3/envs/agr/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/ahmed/anaconda3/envs/agr/lib/site_perl/5.26.2 /home/ahmed/anaconda3/envs/agr/lib/5.26.2/x86_64-linux-thread-multi /home/ahmed/anaconda3/envs/agr/lib/5.26.2 .) at /home/ahmed/anaconda3/envs/agr/bin/snippy line 11.
BEGIN failed--compilation aborted at /home/ahmed/anaconda3/envs/agr/bin/snippy line 11.
Strangely, I have snippy on another conda environment and working.

I tried the installation on my local PC and on the university server and it is not working on both.

Any clue for help?

**Comment by VishnuRaghuram94** [comment]
Hi Ahmed,

This may be a conda issue, looks like bioperl is not installed properly. Could you try installing agrvate on the env where your snippy works and see if that sorts the issue? 

Thanks,
Vishnu

**Comment by AhmedElsherbini** [comment]
Thanks, Vishnu for your fast response,

Indeed, installing Agrvate inside a snippy environment did solve the snippy problem. However, I am getting another type of error. So, inside the the snsp.log I got 

ERROR: CDS check file '/home/ahmed/Downloads/sa_3-17_vontrhrees-results/sa_3-17_vontrhrees-snippy/reference/./ref/cds.fa' not found.
ERROR: Protein check file '/home/ahmed/Downloads/sa_3-17_vontrhrees-results/sa_3-17_vontrhrees-snippy/reference/./ref/protein.fa' not found.
ERROR: Database check failed

and this render snippy with this error

Error running command, check sa_3-17_vontrhrees-results/sa_3-17_vontrhrees-snippy/snps.log

**Comment by VishnuRaghuram94** [comment]
https://github.com/tseemann/snippy/issues/508 - this appears to be the same error you have. Please let me know if it works

Thanks

**Comment by AhmedElsherbini** [comment]
Thank you very much, Vishnu.

It is working now.
